# Generated by Django 5.2.15 on 2026-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer'),
        ),
    ]
