# Generated by Django 5.2.15 on 2026-07-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='password',
        ),
    ]
