# Generated by Django 5.2.15 on 2026-07-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
