# Generated by Django 5.2.15 on 2026-07-16 08:38

import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=order.models.generated_code, max_length=50)),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('max_discount_amount', models.PositiveIntegerField(default=150000)),
                ('limit', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('used_times', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
