# Generated by Django 5.2.15 on 2026-07-16 16:13

import django.db.models.deletion
import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_street'),
        ('order', '0003_order_final_price_order_shipping_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='limit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='text',
            field=models.CharField(default=order.models.generated_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='address.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
