# Generated by Django 5.2.15 on 2026-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_discount_alter_discount_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال آماده سازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شد'), ('canceled', 'لغو شده'), ('returned', 'مرجوع شده'), ('expired', 'منقضی شده')], default='pending', max_length=20),
        ),
    ]
