# Generated by Django 5.2.15 on 2026-08-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_created_at_orderitem_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
